### Register
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "firstName":"Doctor", 
    "lastName":"Strange", 
    "email":"doctorstrange@marvel.com", 
    "password": "DoctorStrange123", 
    "location":"New York City", 
    "occupation":"SuperHero"
}

### Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email":"doctorstrange@marvel.com", 
    "password": "DoctorStrange123"
}

### Create New post
POST http://localhost:5000/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MDg5ZTQyMGZkZWEzM2RlMzA4MDRiOCIsImlhdCI6MTY5NTA2MzgzOX0.VjNyVSyaj8HC_sXZrtY-_a84Js_RTSutQtDQB-vdJ34

{
    "description":"Hi! I am Doctor Stephen Strange", 
    "userId": "65089e420fdea33de30804b8",
    "url":""
}